-- Run this ONCE in your Supabase SQL editor — and run it FIRST, before any
-- other migration in this folder. Every other migration (customer_order_rpc,
-- reset_sequence_rpc, customer_blocklist) assumes this table already exists.

create table if not exists orders (
    id         bigint generated by default as identity primary key,
    data       jsonb  not null,
    updated_ms bigint not null default (extract(epoch from now()) * 1000)
);

alter table orders enable row level security;

drop policy if exists "anon can read and write orders" on orders;
create policy "anon can read and write orders"
    on orders for all
    using (true)
    with check (true);

-- Enable Realtime so the admin app gets new/updated orders instantly
alter publication supabase_realtime add table orders;
